--CREATE TABLE OF CUSTOMERS
CREATE TABLE customers(
CustomerID INT PRIMARY KEY,
Name VARCHAR(50),
Email VARCHAR(50),
Address VARCHAR(100)
);

--INSERT CUSTOMER RECORDS
INSERT INTO customers(CustomerID,Name,Email,Address)
VALUES
(1,'Alice','alice@example.com','Ahmedabad'),
(2,'Bob','bob@example.com','SURAT'),
(3,'Johan','johan@example.com','Delhi'),
(4,'Charlie','charlie@example.com','Ahmedabad'),
(5,'Emma','emma@example.com','Surat');

--RETRIVE ALL CUSTOMER DETAIL
SELECT*FROM customers;

--UPDATE CUSTOMER ADDRESS
UPDATE customers
SET Address='Ahmedabad'
WHERE CustomerID=2;

--DELETE CUSTOMER USING CUSTOMER ID
DELETE FROM customers WHERE CustomerID=2;

--DISPLAY ALL CUSTOMER WHOSE NAME IS 'ALICE'
SELECT*FROM customers WHERE Name='Alice'

--CREATE ORDER TABLE
CREATE TABLE Orders(
OrderID INT PRIMARY KEY,
CustomerID INT ,
OrderDate DATE,
TotalAmount DECIMAL(10,2),
FOREIGN KEY (CustomerID) REFERENCES
customers(CustomerID)
);

--INSERT ORDER RECORD
INSERT INTO Orders(OrderID,CustomerID,OrderDate,TotalAmount)
VALUES
(101,1,'2026-01-09',2500.00),
(102,2,'2026-02-10',7500.36),
(103,3,'2026-04-20',2200.76),
(104,4,'2026-05-18',4000.00),
(105,5,'2026-09-11',4500.99);

--RETRIVE ALL ORDER MADE BY SPECIFIC CUSTOMER
SELECT*FROM Orders WHERE CustomerID=1;

--UPDATE ORDER TOTAL AMOUNT
UPDATE Orders
SET TotalAmount=3000.00
WHERE OrderID=1

--DELETE ORDER USING CUSTOMERID
DELETE FROM Orders WHERE CustomerID=1;

--RETRIVE ORDERS PLACED LASTO 30 DAYS
SELECT*FROM Orders 
WHERE OrderDate>=CURRENT_DATE-INTERVAL '30 days';

--RETRIVE HIGHEST,LOWEST,AND AVERAGE ORDER AMOUNT USING AGGREGATE FUNCTIONS
SELECT  
MAX(TotalAmount)AS HighestAmount,
MIN(TotalAmount)AS LowestAmount,
AVG(TotalAmount )AS AverageAmount
FROM Orders;

--PRODUCTS TABLE
CREATE TABLE Products(
ProductID INT PRIMARY KEY,
ProductName VARCHAR(100),
Price DECIMAL(10,2),
Stock INT
) ;

--INSERT RECORD INTO PRODUCTS TABLE
INSERT INTO Products(ProductID,ProductName,Price,Stock)
VALUES
(201,'Laptop',25000.00,15),
(202,'Mouse',2000.00,20),
(203,'Charger',3000.66,25),
(204,'Keyboard',1200.75,10),
(205,'Headphones',2700.00,25);

--RETRIVE ALL PRODUCTS SORTED BY PRICE DESCENDING ORDER

SELECT*FROM Products Order BY Price DESC;

--UPDATE PRICE SPECIFIC ORDER
UPDATE Products
SET Price=2500.75
WHERE ProductID=201;

--DELETE PRODUCTS IF ITS OUT OF STOCK
DELETE FROM Products WHERE Stock=0;

--RETRIVE PRODUCT WHOSE PRICE BETWEEN $500 AND 200;
SELECT*FROM Products WHERE Price BETWEEN 500.00 AND 2000.00

--RETRIVE MOST EXPENSIVE AND CHEAPEST PRODUCT USING MAX() AND MIN()

SELECT MAX(Price) AS MostExpensive FROM Products;

SELECT MIN(Price) AS Cheapest FROM Products; 

-- CREATE ORDERDETAILS TABLE
CREATE TABLE OrderDetails(
Order_Detail_ID INT PRIMARY KEY,
OrderID INT,
ProductID INT,
Quantity INT,
Sub_Total DECIMAL(10,2),
FOREIGN KEY(OrderID)REFERENCES Orders(OrderID),
FOREIGN KEY(ProductID)REFERENCES Products(ProductID)
);

--INSERT ORDER DETAILS TO ORDETAILS TABLE
INSERT INTO OrderDetails(Order_Detail_ID,OrderID,ProductID,Quantity,Sub_Total)
VALUES
(301,101,201,3,3000.00),
(302,102,202,5,2500.35),
(303,103,203,7,4200.75),
(304,104,204,2,1000.00),
(305,105,205,1,500.00);

--RETRIVE ALL ORDER DETAILS FOR SPECIFIC ORDER
SELECT*FROM OrderDetails
WHERE OrderID=101;

--CALCULATE TOTAL REVENUE GENERATED FROM ALL ORDER USING SUM()
SELECT SUM(Sub_Total)
FROM OrderDetails;	

--RETRIVE TOP 3 MOST ORDERED PRODUCTS
SELECT ProductID,SUM(Quantity) AS TotalQty
FROM OrderDetails
GROUP BY ProductID
ORDER BY TotalQty DESC
LIMIT 3;

--COUNT HOW MANY TIME SPECIFIC PRODUCT HAS BEEN SOLD USING COUT
SELECT COUNT(*)
FROM OrderDetails
WHERE ProductID=1;

